- name: Install openjdk17-jre
  apt:
    name: openjdk-17-jre
    state: present

- name: Add zookeeper group
  group:
    name: zookeeper
    state: present

- name: Add zookeeper user
  user:
    name: zookeeper
    state: present
    create_home: no

- name: Download zookeeper sources
  uri:
    url: "https://dlcdn.apache.org/zookeeper/zookeeper-{{ zookeeper_version }}/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz"
    dest: /tmp/zookeeper.tar.gz

- name: Create zookeeper dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: zookeeper
    group: zookeeper
  loop:
    - /opt/zookeeper
    - /var/lib/zookeeper

- name: Unarchive zookeeper bin and conf files
  unarchive:
    src: /tmp/zookeeper.tar.gz
    dest: /opt/zookeeper
    owner: zookeeper
    group: zookeeper
    extra_opts: --strip-components=1
    remote_src: yes