---
- name: System dummy playbook
  hosts: all
  remote_user: root
  become: yes

  roles:
    - { role: rhel-common, tags: [ common, rhel-common ], when: ansible_os_family == "RedHat" }
    - { role: ubuntu-common, tags: [ common, ubuntu-common ], when: ansible_os_family == "Debian" }
    - { role: docker, tags: [ common, docker ] }
    - { role: zookeeper, tags: [ zookeeper ] }
    - { role: clickhouse, tags: [ clickhouse ] }