---
prometheus-centos-1:
  groups: [ monitoring, prometheus ]
  hostvars: { ansible_ssh_user: ahmed, os_type: rhel, ansible_ssh_host: 1.1.1.1 }

proxmox-ub-01:
  groups: [ proxmox ]
  hostvars: { ansible_ssh_user: ahmed, os_type: debian, ansible_ssh_host: 1.1.1.2 }
