---
prometheus-centos-1:
  groups: [ monitoring, prometheus ]
  hostvars: { ansible_ssh_user: ahmed, os_type: rhel }

proxmox-ub-01:
  groups: [ proxmox ]
  hostvars: { ansible_ssh_user: ahmed, os_type: debian }
