---
#proxmox-1:
#  groups: [ proxmox ]
#  hostvars: { ansible_ssh_user: root, ansible_ssh_host: 192.168.120.8 }
#
#proxmox-2:
#  groups: [ proxmox ]
#  hostvars: { ansible_ssh_user: root, ansible_ssh_host: 192.168.121.10 }
