---
prometheus_centos_1:
  groups: [ monitoring, prometheus ]
  hostvars: { ansible_ssh_host: 192.168.122.5, ansible_ssh_user: ahmed }

prometheus_ubuntu_1:
  groups: [ monitoring, prometheus ]
  hostvars: { ansible_ssh_host: 192.168.122.95, ansible_ssh_user: ahmed }
