- name: Update all packages
  yum:
    name: "*"
    update_cache: yes
    state: latest
  async: 3600
  poll: 60
  when: init_system

- name: Install third-party packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - bash-completion
    - python3