- name: Update all packages
  yum:
    name: "*"
    update_cache: yes
    state: latest
  become: true
  become_user: root

- name: Install third-party packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - bash-completion
    - python3
  become: true
  become_user: root
